### ISSUE TITLE
无法启动gopub

### ISSUE THREAD

**Issue by timosir** [lisijie/gopub#1]
[root@muji gopub-v2.0.0]# sh service.sh status
服务不在运行状态
[root@muji gopub-v2.0.0]# sh service.sh start
正在启动 ... 成功, 进程ID: 14606
[root@muji gopub-v2.0.0]# sh service.sh status
服务不在运行状态, 但进程ID文件存在

无法启动，找不到后台进程？ 
这个是什么原因造成的？
OS环境Centos 6.5 64bit 
git version 1.7.1
mysql-5.6

**Comment by lisijie** [comment]
可能是你的配置信息有误，检查下 conf/app.conf 的配置，直接使用 ./gopub  启动看看报什么错误。

**Comment by timosir** [comment]
[root@muji gopub-v2.0.0]# cat conf/app.conf 
appname = gopub
httpport = 8000
runmode = dev

# 数据库配置
db.host = 127.0.0.1
db.user = root
db.password = "123456"               ------------------我自己修改了
db.port = 3306
db.name = gopub
db.prefix = "t_"
db.timezone = "Asia/Shanghai"

# 邮件服务器配置
mail.from = no-reply@example.com
mail.host = smtp.example.com
mail.port = 25
mail.user = username
mail.password = your password

# 数据目录设置
data_dir = /data/golang/src/gopub/data

# 日志文件
log_file = logs/error.log


[root@muji gopub-v2.0.0]# ./gopub 
-bash: ./gopub: Permission denied

**Comment by lisijie** [comment]
看下 gopub 是不是缺少可执行权限，chmod +x ./gopub 加上执行权限再运行。

**Comment by timosir** [comment]
现在可以启动了，默认登录账号和密码是多少 ？
建议：
1，gopub 默认没有执行权限，按理说go build gopub 后生成的gopub会有执行权限，希望在README.md说明
2，说明conf/app.conf  需要根据自己的配置更改相应信息

**Comment by lisijie** [comment]
帐号：admin   密码：admin888

**Comment by timosir** [comment]
恩 ，谢谢，我刚才自己MD5反解密找到密码了、 麻烦再README 添加说明哦、

**Comment by lisijie** [comment]
嗯嗯，已经加了说明
