### ISSUE TITLE
添加跳板机报错ssh: must specify HostKeyCallback

### ISSUE THREAD

**Issue by Lancger** [lisijie/gopub#22]
无法连接到跳板机: 无法连接到服务器 [192.168.99.101:22]: ssh: must specify HostKeyCallback

**Comment by Code-Ken** [comment]
必须有一个HostKeyCallback的回调函数

**Comment by chenyongze** [comment]
ssh: must specify HostKeyCallback

**Comment by Soul-Yang** [comment]
![image](https://user-images.githubusercontent.com/49636487/60584139-03d33b00-9dbf-11e9-8917-1d21f7d9c0bc.png)

**Comment by Soul-Yang** [comment]
![image](https://user-images.githubusercontent.com/49636487/60584793-b8219100-9dc0-11e9-970d-c4aa85c7eda7.png)

**Comment by Lancger** [comment]
谢谢大佬，抽空我去验证下的





------------------ 原始邮件 ------------------
发件人: "灵魂人物"<notifications@github.com>;
发送时间: 2019年7月3日(星期三) 晚上6:31
收件人: "lisijie/gopub"<gopub@noreply.github.com>;
抄送: "翱翔的微笑"<1151980610@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lisijie/gopub] 添加跳板机报错ssh: must specify HostKeyCallback (#22)

**Comment by Lancger** [comment]
3Q
