### ISSUE TITLE
新建发布单时报错

### ISSUE THREAD

**Issue by sshitaime** [lisijie/gopub#8]
Error 1292: Incorrect datetime value: '-0001-11-30 08:00:00' for column 'pub_time' at row 1

**Comment by lisijie** [comment]
已修复

**Comment by lisijie** [comment]
更新SQL：
ALTER TABLE t_task CHANGE pub_time pub_time DATETIME NULL DEFAULT NULL;
ALTER TABLE t_user CHANGE last_login last_login DATETIME NULL DEFAULT NULL;
