### ISSUE TITLE
插入Task失败, pub_time 字段

### ISSUE THREAD

**Issue by silentred** [lisijie/gopub#9]
go1.7 中发现问题，注释中的写法会导致生成非法的datetime, 例如 '00:-23:00' 这种负数，导致task插入失败

service/task.go 97行：改为
```
//task.PubTime = time.Date(0, 0, 0, 0, 0, 0, 0, time.UTC)
task.PubTime = time.Now().Add(12 * time.Hour)
```
可以插入成功。

**Comment by lisijie** [comment]
更新SQL：
ALTER TABLE `t_task` CHANGE `pub_time` `pub_time` DATETIME NULL DEFAULT NULL;
ALTER TABLE `t_user` CHANGE `last_login` `last_login` DATETIME NULL DEFAULT NULL;
